name: C# CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore "ChatbotApp1.sln"

      - name: Check & Fix Code Formatting
        run: dotnet format "ChatbotApp1.sln"

      - name: Build Project
        run: msbuild "ChatbotApp1.sln" /p:Configuration=Releasee
